// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI flow for analyzing solar images to predict storm danger.
 *
 * - analyzeSolarImage - A function that handles the solar image analysis.
 * - AnalyzeSolarImageInput - The input type for the analyzeSolarImage function.
 * - AnalyzeSolarImageOutput - The return type for the analyzeSolarImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSolarImageInputSchema = z.object({
  imageDataUri: z
    .string()
    .describe(
      "A satellite image of the sun or solar phenomena, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeSolarImageInput = z.infer<typeof AnalyzeSolarImageInputSchema>;

const AnalyzeSolarImageOutputSchema = z.object({
  dangerAssessment: z.string().describe('A textual assessment of the solar storm danger, e.g., Low, Moderate, High, Severe, Extreme.'),
  detailedAnalysis: z.string().describe('A detailed explanation of the features observed in the image and the reasoning for the danger assessment.'),
});
export type AnalyzeSolarImageOutput = z.infer<typeof AnalyzeSolarImageOutputSchema>;

export async function analyzeSolarImage(input: AnalyzeSolarImageInput): Promise<AnalyzeSolarImageOutput> {
  return analyzeSolarImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSolarImagePrompt',
  input: {schema: AnalyzeSolarImageInputSchema},
  output: {schema: AnalyzeSolarImageOutputSchema},
  prompt: `You are an expert solar physicist and space weather forecaster.
Analyze the provided image of solar activity.
Identify any sunspots (note their complexity and size), solar flares (note their intensity and location), coronal mass ejections (CMEs) (note their size, speed, and direction if discernible), filaments, or other relevant phenomena.
Based on your observations of these features in the image, assess the potential danger level of a solar storm originating from the observed activity.
The danger assessment should be one of: Low, Moderate, High, Severe, Extreme.
Provide a detailed analysis explaining the features you observed and how they contribute to your danger assessment.

Image for analysis: {{media url=imageDataUri}}`,
});

const analyzeSolarImageFlow = ai.defineFlow(
  {
    name: 'analyzeSolarImageFlow',
    inputSchema: AnalyzeSolarImageInputSchema,
    outputSchema: AnalyzeSolarImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
