// This is an autogenerated file from Firebase Studio. DO NOT EDIT.
'use server';

import { forecastKpIndex, type KpIndexForecastingInput, type KpIndexForecastingOutput } from '@/ai/flows/kp-index-forecasting';
import type { SolarWindDataInput } from '@/types';

export interface PredictionResult {
  data?: KpIndexForecastingOutput;
  error?: string;
}

export async function handleKpIndexPrediction(
  solarWindData: SolarWindDataInput,
  modelDataUri: string
): Promise<PredictionResult> {
  try {
    const input: KpIndexForecastingInput = {
      solarWindData,
      modelDataUri,
    };
    const result = await forecastKpIndex(input);
    return { data: result };
  } catch (err) {
    console.error('Error in Kp-index prediction:', err);
    // Check if err is an instance of Error to safely access message property
    const errorMessage = err instanceof Error ? err.message : 'An unexpected error occurred during prediction.';
    return { error: errorMessage };
  }
}
