
// This is an autogenerated file from Firebase Studio. DO NOT EDIT.
'use server';

import { forecastKpIndex, type KpIndexForecastingInput, type KpIndexForecastingOutput } from '@/ai/flows/kp-index-forecasting';
import { analyzeSolarImage, type AnalyzeSolarImageInput, type AnalyzeSolarImageOutput } from '@/ai/flows/analyze-solar-image-flow';
import { getRealtimeSolarWindDataTool } from '@/ai/tools/get-realtime-solar-wind-tool';
import type { SolarWindDataInput } from '@/types';

export interface PredictionResult {
  data?: KpIndexForecastingOutput;
  error?: string;
}

export interface SolarImageAnalysisResult {
  data?: AnalyzeSolarImageOutput;
  error?: string;
}

export interface RealtimeSolarWindResult {
  data?: SolarWindDataInput;
  error?: string;
}

export async function handleKpIndexPrediction(
  solarWindData: SolarWindDataInput,
  modelDataUri: string
): Promise<PredictionResult> {
  try {
    const input: KpIndexForecastingInput = {
      solarWindData,
      modelDataUri,
    };
    const result = await forecastKpIndex(input);
    return { data: result };
  } catch (err) {
    console.error('Error in Kp-index prediction:', err);
    const errorMessage = err instanceof Error ? err.message : 'An unexpected error occurred during Kp-index prediction.';
    return { error: errorMessage };
  }
}

export async function handleSolarImageAnalysis(
  imageDataUri: string
): Promise<SolarImageAnalysisResult> {
  try {
    const input: AnalyzeSolarImageInput = { imageDataUri };
    const result = await analyzeSolarImage(input);
    return { data: result };
  } catch (err) {
    console.error('Error in solar image analysis:', err);
    const errorMessage = err instanceof Error ? err.message : 'An unexpected error occurred during image analysis.';
    return { error: errorMessage };
  }
}

export async function fetchLatestSolarWindData(): Promise<RealtimeSolarWindResult> {
  try {
    // Assuming the tool takes no input for "latest"
    const result = await getRealtimeSolarWindDataTool({}); 
    return { data: result };
  } catch (err) {
    console.error('Error fetching real-time solar wind data:', err);
    const errorMessage = err instanceof Error ? err.message : 'An unexpected error occurred while fetching real-time data.';
    return { error: errorMessage };
  }
}
